# Generated by Django 4.2.4 on 2023-08-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0002_request_completion_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='completion_datetime',
        ),
    ]
