# Generated by Django 4.2.4 on 2023-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0003_remove_request_completion_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
