# Generated by Django 4.2.4 on 2023-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0004_request_completion_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='req_response',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
