# Generated by Django 4.2.4 on 2023-08-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0005_request_req_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='req_response',
        ),
    ]
