# Generated by Django 4.2.4 on 2023-08-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0007_request_req_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='req_type',
        ),
    ]
