# Generated by Django 4.2.4 on 2023-08-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0008_remove_request_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='req_type',
            field=models.CharField(default='general', max_length=16),
            preserve_default=False,
        ),
    ]
