# Generated by Django 4.2.4 on 2023-08-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0009_request_req_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='completion_datetime',
        ),
    ]
