# Generated by Django 4.2.4 on 2023-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0010_remove_request_completion_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, upload_to='RequestHandler/files/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('declined', 'Declined')], max_length=16),
        ),
    ]
